# Generated by Django 5.0.1 on 2024-01-13 05:44

import engine.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True, verbose_name='Sub Título')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='Autor')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=engine.core.models.upload_image_formated, verbose_name='Foto')),
                ('created', models.DateTimeField(verbose_name='Criado_em')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
